### ISSUE TITLE
Consider adding variable for response timeout

### ISSUE THREAD

**Issue by zieg8301** [scaleoutsean/hcicollector#12]
Current response timeout is hardcoded to 10 seconds:

https://github.com/scaleoutsean/hcicollector/blob/cf1d355af71d6fbba8b7dff5d0eb481948bc6a61/sfcollector/solidfire_graphite_collector.py#L449

Opening an issue to start a conversation about creating a user-definable parameter for response timeout. We have a couple SF clusters in our org that take longer than 10 seconds to return API results for ListNodeStats.

Workaround: Hardcoding an extended timeout.

**Comment by scaleoutsean** [comment]
I figured if there's no response within 10 seconds, it's better to drop it, but I don't run large clusters so maybe in "real life" it does take longer.
There was a situation (although this is based on 2nd hand info) where Master failover supposedly caused HCICollector to get stuck for minutes. 
The other reason - I haven't checked this lately but based on my recollection - is that statsd currently tags metrics with statsd time, so if response is returned in say 70 seconds and the next call returns quickly, we'd have to look into what happens if 2 responses are received in the same interval.

But yes we can certainly add a user-defined param here.

**Comment by scaleoutsean** [comment]
The timestamp thing is in graphyte - if there's no time stamp in the metric, it creates its own at the time of sending. So I think this could make timestamps of delayed metrics jump into the next minute. 

https://github.com/benhoyt/graphyte/blob/90c659aede8dcbf624e1b9c2f0fbb42100b80259/graphyte.py#L101

**Comment by scaleoutsean** [comment]
This seems solved, as far as the API allows. Please reopen if still a problem.
